import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DataContextProvider from "@/context/dataContext";
import PlayerContextProvider from "@/context/playerContext";
import ScaleContextProvider from "@/context/scaleContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataContextProvider>
          <ScaleContextProvider>
            <PlayerContextProvider>{children}</PlayerContextProvider>
          </ScaleContextProvider>
        </DataContextProvider>
      </body>
    </html>
  );
}
